### ISSUE TITLE
About Varnish service startup

### ISSUE THREAD

**Issue by mozgbrasil** [SemanticComputing/docker-varnish#1]
Hello good afternoon

# About Varnish service startup

As images at startup the service is being displayed error 503 can help me

![captura de tela de 2019-01-28 11-37-42](https://user-images.githubusercontent.com/17202780/51840275-c4c22a80-22f2-11e9-8526-916e38e7ba0c.png)
![captura de tela de 2019-01-28 11-37-49](https://user-images.githubusercontent.com/17202780/51840276-c4c22a80-22f2-11e9-84a3-5bd4e04ddf2d.png)
![captura de tela de 2019-01-28 11-47-57](https://user-images.githubusercontent.com/17202780/51840277-c4c22a80-22f2-11e9-8cc0-535fb188fed7.png)

**Comment by yoge1** [comment]
You need to have at least one [backend server](https://varnish-cache.org/docs/trunk/users-guide/vcl-backends.html) for Varnish. This Varnish Docker image does not contain an HTTP server for the backend, so you need to install it by yourself. By default, the image has 127.0.0.1:8080 configured as the backend server (port 8080 in the same container, i.e. not on the host machine).

You can change the default backend IP and PORT by using the environment variables VARNISH_BACKEND_IP and VARNISH_BACKEND_PORT (by setting them in [Dockerfile](https://docs.docker.com/engine/reference/builder/#env) or [as parameters / in env file](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file) of the docker run command) or writing the site configuration in a VCL file (e.g. site.vcl) and copying it into the container (in Dockerfile: COPY site.vcl "$FILE_SITE_VCL"). You can for example have an HTTP server running in its own container in the same Docker network as the Varnish container, and use it as a backend.
